server:
  port: ${PORT:8080}

spring:
  main:
    banner-mode: console
  data:
    mongodb:
      uri: 'mongodb://127.0.0.1:27017/pets'

token:
  salt: JpxM4e858rc673syopdZnMFb*ExeqJtUc0HJ_iOxu~jiSYu+yPdPw93OBBjF
  expirationMs: 86400000

allowed.origin: 'http://localhost:3000'

logging:
  level:
    root: info

cloudinary:
  cloudName: 'dtwihdglb'
  apiKey: '253513754387222'
  apiSecret: '1YKZO7Z4KK0xuf3CEXM1JvcQchA'

