server:
  port: ${PORT:8080}

spring:
  main:
    banner-mode: console
  data:
    mongodb:
      uri: 'mongodb://127.0.0.1:27017/pets'
  mail:
    host: 'smtp.gmail.com'
    port: 587
    username: 'petfndr@gmail.com'
    password: CwXt|'S4q|>>
    smtp:
      auth: true
      starttls.enable: true

token:
  salt: JpxM4e858rc673syopdZnMFb*ExeqJtUc0HJ_iOxu~jiSYu+yPdPw93OBBjF
  expirationMs: 86400000

allowed.origin: 'http://localhost:3000'

logging:
  level:
    root: info



