server:
  port: ${PORT:8080}

spring:
  main:
    banner-mode: console
  data:
    mongodb:
      uri: 'mongodb://127.0.0.1:27017/pets'
  mail:
    host: 'smtp.gmail.com'
    port: 587
    username: petfnder@gmail.com
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 699410328807-c4uv0d4jtn0udkm110toeu9cs4h87371.apps.googleusercontent.com
            client-secret: kmTucwGpXKZofoIF9raDNhyn
            redirectUri: "http://localhost:8080/login/oauth2/code/google"
            scope:
              - email
          facebook:
            client-id: 267623958479461
            client-secret: 651c202edb7fba425d822c50f89e0794
            scope:
              - email
          vk:
            clientName: vk
            clientId: ${VK_CLIENT_ID:7876580}
            clientSecret: ${VK_CLIENT_SECRET:zQ2R9CACCpjdwp7CQqTb}
            redirectUri: ${VK_REDIRECT_URI:http://localhost:8080/login/oauth2/code/vk}
            authorizationGrantType: authorization_code
            clientAuthenticationMethod: basic
            scope: email
            authorizationUri: https://oauth.vk.com/authorize
            tokenUri: https://oauth.vk.com/access_token
            userInfoUri: https://api.vk.com/method/users.get
            provider: vk
        provider:
          vk:
            authorizationUri: https://oauth.vk.com/authorize
            tokenUri: ${VK_TOKEN_URI:https://oauth.vk.com/access_token?client_id=${VK_CLIENT_ID:7876580}&client_secret=${VK_CLIENT_SECRET:zQ2R9CACCpjdwp7CQqTb}}
            userInfoUri: https://api.vk.com/method/users.get?v=5.89
            userNameAttribute: id

token:
  salt: JpxM4e858rc673syopdZnMFb*ExeqJtUc0HJ_iOxu~jiSYu+yPdPw93OBBjF
  expirationMs: 86400000

allowed.origin: 'http://localhost:3000'

oauth2:
  authorizedRedirectUri: http://localhost:3000/

logging:
  level:
    root: info

