server:
  port: 8080

spring:
  main:
    banner-mode: console
  data:
    mongodb:
      uri: 'mongodb://127.0.0.1:27017/pets'

token:
  salt: JpxM4e858rc673syopdZnMFb*ExeqJtUc0HJ_iOxu~jiSYu+yPdPw93OBBjF
  expirationMs: 86400000

logging:
  level:
    root: debug
